n=float(input('Digite um número: '))
print(n)
print(type(n))
n1=str(input('Digite um valor: '))
print(n1)
print(type(n1))
n2=bool(input('Digite o valor: '))
print(n2)
print(type(n2))
n3=int(input('Digite o número: '))
print(n3)
print(type(n3))
