frase=str('Hello World!')
print(frase[3])
print(frase[2:6])
print(frase[0:12])
print(frase[2:])
print(frase[:9])
print(frase[0:12:2])
print(frase[0::2])
print(frase.count('o'))
print(frase.find('ello'))
print(frase.count('o',0,6))
print(frase.upper().count('O'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
