n=int(input('Escolha um número: '))
n1=n*1
n2=n*2
n3=n*3
n4=n*4
n5=n*5
n6=n*6
n7=n*7
n8=n*8
n9=n*9
n10=n*10
print(n,'* 1 = {}'.format(n1))
print(n,'* 2 = {}'.format(n2))
print(n,'* 3 = {}'.format(n3))
print(n,'* 4 = {}'.format(n4))
print(n,'* 5 = {}'.format(n5))
print(n,'* 6 = {}'.format(n6))
print(n,'* 7 = {}'.format(n7))
print(n,'* 8 = {}'.format(n8))
print(n,'* 9 = {}'.format(n9))
print(n,'* 10 = {}'.format(n10))
